source 'https://github.com/CocoaPods/Specs.git'

target 'SBTextInputView', :exclusive => true do
  pod 'SBTextInputView', :path => '../'
end

target 'Tests', :exclusive => true do
  pod 'SBTextInputView', :path => '../'

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
