source 'https://github.com/CocoaPods/Specs.git'

target 'SBTextInputView' do
  pod 'SBTextInputView', :path => '../'
end

target 'Tests' do
  pod 'SBTextInputView', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'Expecta+Snapshots'
end
